version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=R9xxzmspqhKhJ7R
    volumes:
      - ./volume/data:/var/lib/mysql:rw
    networks:
      - deploy
    restart: always
    command:
      - --innodb_flush_log_at_trx_commit=2

networks:
  deploy: